[package]
name = "beta-one"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston2d-graphics = "0.42.0"
arrayvec = "0.7.2"
regex = "1"
